### ISSUE TITLE
Investigate the use of VM Scale Sets for pool orchestration

### ISSUE THREAD

**Issue by anderm** [CatalystCode/3DStreamingToolkit#207]
Related to #183  

VMSS are a potential for the orchestrator implementation.

**Comment by shahedc** [comment]
Identified that Azure Batch API is the best option to create VMs using either Cloud Service Configuration or VM Configuration when creating a pool with CreatePool, so it won't be necessary to work with Scale Sets directly. 

Note that the official documentation mentions that "_The Batch service uses virtual machine scale sets to provide Linux compute nodes_" when creating a Linux VM from an image using Virtual Machine Configuration. FYI, "_Cloud Services Configuration provides Windows compute nodes only_". 

Reference: [https://docs.microsoft.com/en-us/azure/batch/batch-linux-nodes](https://docs.microsoft.com/en-us/azure/batch/batch-linux-nodes)
