### ISSUE TITLE
Investigate and decide on a different name for the toolkit

### ISSUE THREAD

**Issue by anderm** [CatalystCode/3DStreamingToolkit#218]
3dtoolkit is a very generic term and does not represent the solution presented by this toolkit. We need to find a better name!

**Comment by rozele** [comment]
_Names should have a good-faith, common-sense name. ... we do not invent new code words, product code names, or "cute project names". Internal naming disputes should be resolved between responsible repository maintainers._

_... it's important that repositories have a consistent, fair name. Common sense should be used in naming a repository. Corporate policy prohibiting the creation of code names and unofficial names must be followed._

_Teams should take care to not create repositories which "burn" the best name for a project: as an example, a team building an open source Visual Studio extension to interact with the Service Bus product should not create a new repository named "service-bus", but instead something more specific, such as "service-bus-vs-extension", leaving the "service-bus" name for the official product team's use if ever needed._

**Comment by anderm** [comment]
Closed with #242
