### ISSUE TITLE
migrate existing tests to gtest

### ISSUE THREAD

**Issue by bengreenier** [CatalystCode/3DStreamingToolkit#225]
This issue tracks the migration of existing unit tests to the `gtest` framework as opposed to mstest. This aligns more closely with `webrtc` in the first place, and still allows tests to be run easily in a dev environment using [csoltenborn/GoogleTestAdapter](https://github.com/csoltenborn/GoogleTestAdapter).

**Comment by anderm** [comment]
Closed with #226
