### ISSUE TITLE
support CI running of gtest tests

### ISSUE THREAD

**Issue by bengreenier** [CatalystCode/3DStreamingToolkit#231]
As we [migrate to gtest](https://github.com/CatalystCode/3dtoolkit/pull/226) we'll need to modify our CI build to run those tests.

**Comment by anderm** [comment]
All gtests are running successfully in our PR and CI builds https://dpeted.visualstudio.com/TED%20Strategic%20Engagements%20(Agile)/_build?path=%5C&_a=allDefinitions
