### ISSUE TITLE
Update ci to include gtest

### ISSUE THREAD

**Issue by bengreenier** [CatalystCode/3DStreamingToolkit#241]
Today we use `vstest` for the official ci build, but per #226 we'll switch to gtest. We need to swap vstest for gtest running in the offical ci build as a result. This tracks that work item.

**Comment by anderm** [comment]
Our PR and CI builds are now officially triggering gtest 
Test Results
Total tests: 16
Passed: 16
Failed: 0
Pass percentage: 100%
Total run duration: 0:00:00.09

**Comment by anderm** [comment]
Closed with #231
