### ISSUE TITLE
Visual Studio 15.7.3/4 and Google Test Adapter are incomptible

### ISSUE THREAD

**Issue by KanishkT123** [CatalystCode/3DStreamingToolkit#261]
## Report

- [X] I have searched [existing issues](https://github.com/CatalystCode/3DStreamingToolkit/issues) and this is not a duplicate.

## Environment

- Visual Studio Version: 15.7.3/15.7.4
- Google Test Adapter V1.0

## Issues and Steps to Reproduce
`#include <gtest/gtest.h>` is in any document.

## Expected Behavior
The GTest environment is already set up and the GTest adapter should be working normally. Therefore google tests should run and build normally.

## Actual Behavior
VS Intellisense throws a "source file not found" error and the code has build errors. None of the GTEST features, such as `ASSERT_TRUE` are available on the IDE.

**Comment by KanishkT123** [comment]
The developer command prompt for VS2017 seems to work to actually build the projects. However, the intellisense IDE does not build them for some reason. 

There are potential workarounds, such as manually downloading Gtest and making it an additional included directory so that VS2017 knows where to look. However, unless either VS2017 or the GTest adapter are fixed this problem will remain.

**Comment by bengreenier** [comment]
@KanishkT123 did you try a visual studio build, (installs gtest), then close and reopen solution? sometimes intelisense doesn't work quite right when it comes to picking up new files

**Comment by KanishkT123** [comment]
I tried it, it's still giving me errors, all of which are gtest related.

**Comment by bengreenier** [comment]
@KanishkT123 does vs build it successfully despite the intelisense errors?

**Comment by KanishkT123** [comment]
On the dev prompt it does. Weirdly, if I shut the tests file and build it, it does build successfully in VS. So just having the file not actually be open so intellisense can't analyze it seems to work.

**Comment by KanishkT123** [comment]
Seems to be resolved, after it builds once the problem is resolved as gtest gets initialized/created.
