### ISSUE TITLE
Functional end-to-end test on a local machine with the DX server/multiple clients

### ISSUE THREAD

**Issue by phongcao** [CatalystCode/3DStreamingToolkit#266]
We need to write an end-to-end functional test with a local DirectX server and at least two clients. This will be integrated into our CI build and should test the following flow:

Rendering of a scene
Grabbing the frame
Encoding the frame
RTP packaging
Package sent and received via a TURN server
RTP de-packaging
Decoding the frame
Rendering the frame

**Comment by anderm** [comment]
Closed with #272
