### ISSUE TITLE
x86 compatible build versions for the Native Streaming Server Plugin

### ISSUE THREAD

**Issue by KanishkT123** [CatalystCode/3DStreamingToolkit#268]
## Report

- [X] I have searched [existing issues](https://github.com/CatalystCode/3DStreamingToolkit/issues) and this is not a duplicate.

## Issues and Steps to Reproduce
The Native Streaming Server plugin does not have a x86 Debug/Release build configuration, which should be supported. 

## Expected Behavior
When building with vcpkg, the correct configurations are supported. 

## Actual Behavior
x86 release and x86 debug both fail to build.

**Comment by anderm** [comment]
As explained in the docs, this behavior is expected. Note: We no longer support x86 server builds that are using nvencode. This is due to 32-bit support gradually being deprecated/removed from CUDA. Closing
