### ISSUE TITLE
WebClient pcConfigStatic not defined

### ISSUE THREAD

**Issue by RabanserD** [CatalystCode/3DStreamingToolkit#270]
## Report

- [x] I have searched [existing issues](https://github.com/CatalystCode/3DStreamingToolkit/issues) and this is not a duplicate.

## Environment

- OS Version: Win10 v1803 x64

## Issues and Steps to Reproduce
Not defined pcConfigStatic causes the web client to not work

## Expected Behavior
WebClient should connect to the Signal Server and retreive a list of Available Render Servers

## Actual Behavior
WebClient frontendconnects to the Signal Server but does not get a list of Available Render Servers.
Error:
Uncaught ReferenceError: pcConfigStatic is not defined
    at HTMLButtonElement.connect (app.js:259)

**Comment by RabanserD** [comment]
As a workaround I edited the following in app.js for now:
'peerConnectionConfig': pcConfigStatic -> 'peerConnectionConfig': pcConfigSTUNStatic

**Comment by anderm** [comment]
@RabanserD thanks for creating this issue! We recently upgraded our web client and the js-3dstk library #263. Please get latest and let us know if you still have any issues

**Comment by RabanserD** [comment]
Hi @anderm , thanks, with the new release it works!
