### ISSUE TITLE
Write a tutorial on how to run the end-to-end tests

### ISSUE THREAD

**Issue by anderm** [CatalystCode/3DStreamingToolkit#271]
Our end-to-end tests are very powerful but require a few steps to setup. We need to write a tutorial on how to run them and what results to expect.

**Comment by anderm** [comment]
Wrote a tutorial here: https://github.com/CatalystCode/3DStreamingToolkit/wiki/Running-functional-tests-tutorial. @phongcao please review when you can and we can close this

**Comment by phongcao** [comment]
Looks awesome to me @anderm! Thanks a lot for helping me write this tutorial.

**Comment by phongcao** [comment]
I'll merge this PR after adding the info about multi-clients test.

**Comment by phongcao** [comment]
[Wiki](https://github.com/CatalystCode/3DStreamingToolkit/wiki/Running-functional-tests-tutorial#one-rendering-server-connects-to-multiple-clients-test) has been updated. Closing.
